language: python
python: 2.7
install:
    - python setup.py install
    - pip install tox
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pypy
  global:
  - secure: ZZ2hIW6D36WKyPOhLAkCcA7lqa8lV8ty8aHrJSONa83DMEbp0NasBqBpPSX0Awp3DPniNnGCn3kPIZXwx/sJuSMCKitmAu4HtYynTK2yhv+A/JJsmnBLMm1OlBZWJ6FJ9LszuZIvXSCA1MLk7QvY5olqqFp1UYEh7ep9CueL9dY=
  - secure: bMh9I7FhrQOBm5w7VwuyvyB1s2SyelIy/xHM1q1gnH5PZbua0t7DzFlhVwbXY8rXoNIiPGzJlnZ6VeAA3atObJNbkxGQmQ41ZVReT1I8M9VPHQaz/dkBW9mO+QIBchgONuciT87uAa3SmP5gxPSAP5EGNpKT7p2K6iIgzIOYB68=
script: tox -e $TOX_ENV